export const plantType = {
  wheat: {
    isBlocked: false,
    growTime: 3500,
    howThirsty: 2,
    seed: "🫘",
    seedling: "🌱",
    ready: "🌾",
    buyPrice: 1,
    sellPrice: 2,
  },
  corn: {
    isBlocked: true,
    growTime: 5000,
    howThirsty: 5,
    seed: "🫘",
    seedling: "🌿",
    ready: "🌽",
    buyPrice: 2,
    sellPrice: 5,
  },
  carrot: {
    isBlocked: true,
    growTime: 2000,
    howThirsty: 3,
    seed: "𓇢",
    seedling: "🌱",
    ready: "🥕",
    buyPrice: 2,
    sellPrice: 4,
  },
  onion: {
    isBlocked: true,
    growTime: 2500,
    howThirsty: 3,
    seed: "𓇢",
    seedling: "🍀",
    ready: "🧅",
    buyPrice: 1,
    sellPrice: 3,
  },
};
